name: Quarkus build and test

on:
  push:
    branches:
      - quarkus
    paths-ignore:
      - '**/*.md'
      - '.github/dependabot.yml'
      - '.github/workflows/quarkus-build-test.yml'
  pull_request:
    branches:
      - quarkus
    paths-ignore:
      - '**/*.md'
      - '.github/dependabot.yml'
      - '.github/workflows/quarkus-build-test.yml'
  workflow_dispatch:

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  jvm-build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java:
          - '17'
          - '21'
    services:
      ollama:
        image: ollama/ollama
        ports:
          - 11434:11434
    name: "jvm-build-test-${{ matrix.java }}"
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: maven

      - name: Install playwright dependencies
        run: |
          sudo npx playwright install-deps
          npx playwright install

      - name: "build-test-jvm-java${{ matrix.java }}"
        run: |
          ./mvnw -B clean verify \
            -Dquarkus.profile=ollama \
            -Dquarkus.test.profile=ollama,test \
            -Dquarkus.test.integration-test-profile=ollama,prod \
            -Dquarkus.http.host=0.0.0.0 \
            -Dmaven.compiler.release=${{ matrix.java }}